.TH "AuData.h" 3 "Thu Aug 17 2017" "Version 0.5.1" "steghide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AuData.h
.SH SYNOPSIS
.br
.PP
\fC#include 'BinaryIO\&.h'\fP
.br
\fC#include 'AudioData\&.h'\fP
.br

.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef \fBAudioDataImpl\fP< \fBAuMuLaw\fP, \fBBYTE\fP > \fBAuMuLawAudioData\fP"
.br
.ti -1c
.RI "typedef \fBAudioDataImpl\fP< \fBAuPCM8\fP, \fBSBYTE\fP > \fBAuPCM8AudioData\fP"
.br
.ti -1c
.RI "typedef \fBAudioDataImpl\fP< \fBAuPCM16\fP, \fBSWORD16\fP > \fBAuPCM16AudioData\fP"
.br
.ti -1c
.RI "typedef \fBAudioDataImpl\fP< \fBAuPCM32\fP, \fBSWORD32\fP > \fBAuPCM32AudioData\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef \fBAudioDataImpl\fP<\fBAuMuLaw\fP,\fBBYTE\fP> \fBAuMuLawAudioData\fP"

.SS "typedef \fBAudioDataImpl\fP<\fBAuPCM16\fP,\fBSWORD16\fP> \fBAuPCM16AudioData\fP"

.SS "typedef \fBAudioDataImpl\fP<\fBAuPCM32\fP,\fBSWORD32\fP> \fBAuPCM32AudioData\fP"

.SS "typedef \fBAudioDataImpl\fP<\fBAuPCM8\fP,\fBSBYTE\fP> \fBAuPCM8AudioData\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for steghide from the source code\&.
