.TH "AudioData" 3 "Thu Aug 17 2017" "Version 0.5.1" "steghide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AudioData \- interface definition for \fBAudioData\fP objects\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <AudioData\&.h>\fP
.PP
Inherits \fBCvrStgObject\fP\&.
.PP
Inherited by \fBAudioDataImpl< Type, ValueType, SampleValueType >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBread\fP (\fBBinaryIO\fP *io, \fBUWORD32\fP n=\fBNoLimit\fP)=0"
.br
.ti -1c
.RI "virtual void \fBwrite\fP (\fBBinaryIO\fP *io, \fBUWORD32\fP n=\fBNoLimit\fP)=0"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const \fBUWORD32\fP \fBNoLimit\fP = 0"
.br
.RI "constant that can be used as parameter to read and write to indicate that there is no limit "
.in -1c
.SH "Detailed Description"
.PP 
This class is necessary to provide one common base class for all types of audio data, i\&.e\&. all different instances of \fBAudioDataImpl\fP\&. 
.SH "Member Function Documentation"
.PP 
.SS "virtual void AudioData::read (\fBBinaryIO\fP * io, \fBUWORD32\fP n = \fC\fBNoLimit\fP\fP)\fC [pure virtual]\fP"

.PP
Implemented in \fBAudioDataImpl< Type, ValueType, SampleValueType >\fP\&.
.SS "virtual void AudioData::write (\fBBinaryIO\fP * io, \fBUWORD32\fP n = \fC\fBNoLimit\fP\fP)\fC [pure virtual]\fP"

.PP
Implemented in \fBAudioDataImpl< Type, ValueType, SampleValueType >\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "const \fBUWORD32\fP AudioData::NoLimit = 0\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for steghide from the source code\&.
