.TH "AudioData.h" 3 "Thu Aug 17 2017" "Version 0.5.1" "steghide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AudioData.h
.SH SYNOPSIS
.br
.PP
\fC#include <vector>\fP
.br
\fC#include 'AudioSampleValue\&.h'\fP
.br
\fC#include 'CvrStgObject\&.h'\fP
.br
\fC#include 'error\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAudioData\fP"
.br
.RI "interface definition for \fBAudioData\fP objects\&. "
.ti -1c
.RI "class \fBAudioDataImpl< Type, ValueType, SampleValueType >\fP"
.br
.RI "implementation of the AudioData-Interface "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for steghide from the source code\&.
