.TH "AuSampleValues.h" 3 "Thu Aug 17 2017" "Version 0.5.1" "steghide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AuSampleValues.h
.SH SYNOPSIS
.br
.PP
\fC#include 'AudioSampleValue\&.h'\fP
.br

.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef \fBAudioSampleValue\fP< \fBAuMuLaw\fP, \fBBYTE\fP > \fBAuMuLawSampleValue\fP"
.br
.ti -1c
.RI "typedef \fBAudioSampleValue\fP< \fBAuPCM8\fP, \fBSBYTE\fP > \fBAuPCM8SampleValue\fP"
.br
.ti -1c
.RI "typedef \fBAudioSampleValue\fP< \fBAuPCM16\fP, \fBSWORD16\fP > \fBAuPCM16SampleValue\fP"
.br
.ti -1c
.RI "typedef \fBAudioSampleValue\fP< \fBAuPCM32\fP, \fBSWORD32\fP > \fBAuPCM32SampleValue\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef \fBAudioSampleValue\fP<\fBAuMuLaw\fP,\fBBYTE\fP> \fBAuMuLawSampleValue\fP"

.SS "typedef \fBAudioSampleValue\fP<\fBAuPCM16\fP,\fBSWORD16\fP> \fBAuPCM16SampleValue\fP"

.SS "typedef \fBAudioSampleValue\fP<\fBAuPCM32\fP,\fBSWORD32\fP> \fBAuPCM32SampleValue\fP"

.SS "typedef \fBAudioSampleValue\fP<\fBAuPCM8\fP,\fBSBYTE\fP> \fBAuPCM8SampleValue\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for steghide from the source code\&.
