.TH "AUtils.h" 3 "Thu Aug 17 2017" "Version 0.5.1" "steghide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AUtils.h
.SH SYNOPSIS
.br
.PP
\fC#include <cmath>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAUtils\fP"
.br
.RI "provides some generic functions for non-standard arithmetic operations "
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBlog2\fP(x)   (log(x) / log(2\&.0))"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define log2(x)   (log(x) / log(2\&.0))"

.SH "Author"
.PP 
Generated automatically by Doxygen for steghide from the source code\&.
