.TH "AUtilsTest" 3 "Thu Aug 17 2017" "Version 0.5.1" "steghide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AUtilsTest
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <AUtilsTest\&.h>\fP
.PP
Inherits \fBUnitTest\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAUtilsTest\fP (\fBTestSuite\fP *s)"
.br
.ti -1c
.RI "void \fBtestLog2\fP (void)"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "bool \fBgenericTestLog2\fP (int n, double res)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "AUtilsTest::AUtilsTest (\fBTestSuite\fP * s)"

.SH "Member Function Documentation"
.PP 
.SS "bool AUtilsTest::genericTestLog2 (int n, double res)\fC [private]\fP"

.SS "void AUtilsTest::testLog2 (void)"


.SH "Author"
.PP 
Generated automatically by Doxygen for steghide from the source code\&.
