.TH "BFSAPHeuristicTest.cc" 3 "Thu Aug 17 2017" "Version 0.5.1" "steghide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BFSAPHeuristicTest.cc
.SH SYNOPSIS
.br
.PP
\fC#include 'BFSAPHeuristic\&.h'\fP
.br
\fC#include 'BitString\&.h'\fP
.br
\fC#include 'Edge\&.h'\fP
.br
\fC#include 'Graph\&.h'\fP
.br
\fC#include 'Matching\&.h'\fP
.br
\fC#include 'Selector\&.h'\fP
.br
\fC#include 'DummyFile\&.h'\fP
.br
\fC#include 'BFSAPHeuristicTest\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBprivate\fP   public"
.br
.ti -1c
.RI "#define \fBprotected\fP   public"
.br
.ti -1c
.RI "#define \fBCREATEEDGE\fP(G,  V1,  V2)   (new \fBEdge\fP ((G)\->getVertex(V1), 0, (G)\->getVertex(V2), 1))"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define CREATEEDGE(G, V1, V2)   (new \fBEdge\fP ((G)\->getVertex(V1), 0, (G)\->getVertex(V2), 1))"

.SS "#define private   public"

.SS "#define protected   public"

.SH "Author"
.PP 
Generated automatically by Doxygen for steghide from the source code\&.
