.TH "BitString.cc" 3 "Thu Aug 17 2017" "Version 0.5.1" "steghide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BitString.cc
.SH SYNOPSIS
.br
.PP
\fC#include 'AUtils\&.h'\fP
.br
\fC#include 'BitString\&.h'\fP
.br
\fC#include 'common\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBBITPOS\fP(n)   (n % 8)"
.br
.ti -1c
.RI "#define \fBBYTEPOS\fP(n)   (n / 8)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define BITPOS(n)   (n % 8)"

.SS "#define BYTEPOS(n)   (n / 8)"

.SH "Author"
.PP 
Generated automatically by Doxygen for steghide from the source code\&.
