.TH "BmpFile.h" 3 "Thu Aug 17 2017" "Version 0.5.1" "steghide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BmpFile.h
.SH SYNOPSIS
.br
.PP
\fC#include <vector>\fP
.br
\fC#include 'CvrStgFile\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBmpFile\fP"
.br
.ti -1c
.RI "struct \fBBmpFile::struct_BITMAPFILEHEADER\fP"
.br
.ti -1c
.RI "struct \fBBmpFile::struct_BITMAPINFOHEADER\fP"
.br
.ti -1c
.RI "struct \fBBmpFile::struct_BITMAPCOREHEADER\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for steghide from the source code\&.
