.TH "BmpFile::struct_BITMAPCOREHEADER" 3 "Thu Aug 17 2017" "Version 0.5.1" "steghide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BmpFile::struct_BITMAPCOREHEADER
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <BmpFile\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned long \fBbcSize\fP"
.br
.ti -1c
.RI "unsigned short \fBbcWidth\fP"
.br
.ti -1c
.RI "unsigned short \fBbcHeight\fP"
.br
.ti -1c
.RI "unsigned short \fBbcPlanes\fP"
.br
.ti -1c
.RI "unsigned short \fBbcBitCount\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "unsigned short BmpFile::struct_BITMAPCOREHEADER::bcBitCount"

.SS "unsigned short BmpFile::struct_BITMAPCOREHEADER::bcHeight"

.SS "unsigned short BmpFile::struct_BITMAPCOREHEADER::bcPlanes"

.SS "unsigned long BmpFile::struct_BITMAPCOREHEADER::bcSize"

.SS "unsigned short BmpFile::struct_BITMAPCOREHEADER::bcWidth"


.SH "Author"
.PP 
Generated automatically by Doxygen for steghide from the source code\&.
