.TH "BmpFile::struct_BITMAPFILEHEADER" 3 "Thu Aug 17 2017" "Version 0.5.1" "steghide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BmpFile::struct_BITMAPFILEHEADER
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <BmpFile\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned short \fBbfType\fP"
.br
.ti -1c
.RI "unsigned long \fBbfSize\fP"
.br
.ti -1c
.RI "unsigned short \fBbfReserved1\fP"
.br
.ti -1c
.RI "unsigned short \fBbfReserved2\fP"
.br
.ti -1c
.RI "unsigned long \fBbfOffBits\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "unsigned long BmpFile::struct_BITMAPFILEHEADER::bfOffBits"

.SS "unsigned short BmpFile::struct_BITMAPFILEHEADER::bfReserved1"

.SS "unsigned short BmpFile::struct_BITMAPFILEHEADER::bfReserved2"

.SS "unsigned long BmpFile::struct_BITMAPFILEHEADER::bfSize"

.SS "unsigned short BmpFile::struct_BITMAPFILEHEADER::bfType"


.SH "Author"
.PP 
Generated automatically by Doxygen for steghide from the source code\&.
