.TH "BmpFile::struct_BITMAPINFOHEADER" 3 "Thu Aug 17 2017" "Version 0.5.1" "steghide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BmpFile::struct_BITMAPINFOHEADER
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <BmpFile\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned long \fBbiSize\fP"
.br
.ti -1c
.RI "signed long \fBbiWidth\fP"
.br
.ti -1c
.RI "signed long \fBbiHeight\fP"
.br
.ti -1c
.RI "unsigned short \fBbiPlanes\fP"
.br
.ti -1c
.RI "unsigned short \fBbiBitCount\fP"
.br
.ti -1c
.RI "unsigned long \fBbiCompression\fP"
.br
.ti -1c
.RI "unsigned long \fBbiSizeImage\fP"
.br
.ti -1c
.RI "signed long \fBbiXPelsPerMeter\fP"
.br
.ti -1c
.RI "signed long \fBbiYPelsPerMeter\fP"
.br
.ti -1c
.RI "unsigned long \fBbiClrUsed\fP"
.br
.ti -1c
.RI "unsigned long \fBbiClrImportant\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "unsigned short BmpFile::struct_BITMAPINFOHEADER::biBitCount"

.SS "unsigned long BmpFile::struct_BITMAPINFOHEADER::biClrImportant"

.SS "unsigned long BmpFile::struct_BITMAPINFOHEADER::biClrUsed"

.SS "unsigned long BmpFile::struct_BITMAPINFOHEADER::biCompression"

.SS "signed long BmpFile::struct_BITMAPINFOHEADER::biHeight"

.SS "unsigned short BmpFile::struct_BITMAPINFOHEADER::biPlanes"

.SS "unsigned long BmpFile::struct_BITMAPINFOHEADER::biSize"

.SS "unsigned long BmpFile::struct_BITMAPINFOHEADER::biSizeImage"

.SS "signed long BmpFile::struct_BITMAPINFOHEADER::biWidth"

.SS "signed long BmpFile::struct_BITMAPINFOHEADER::biXPelsPerMeter"

.SS "signed long BmpFile::struct_BITMAPINFOHEADER::biYPelsPerMeter"


.SH "Author"
.PP 
Generated automatically by Doxygen for steghide from the source code\&.
