.TH "BmpPaletteSampleValue.h" 3 "Thu Aug 17 2017" "Version 0.5.1" "steghide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BmpPaletteSampleValue.h
.SH SYNOPSIS
.br
.PP
\fC#include 'BmpSampleValue\&.h'\fP
.br
\fC#include 'CvrStgFile\&.h'\fP
.br
\fC#include 'ColorPalette\&.h'\fP
.br
\fC#include 'common\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBmpPaletteSampleValue\fP"
.br
.RI "a sample in a bmp palette (i\&.e\&. in a 1-,4- or 8-bit) file "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for steghide from the source code\&.
