.TH "BmpRGBSampleValue.h" 3 "Thu Aug 17 2017" "Version 0.5.1" "steghide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BmpRGBSampleValue.h
.SH SYNOPSIS
.br
.PP
\fC#include 'BmpSampleValue\&.h'\fP
.br
\fC#include 'RGBTriple\&.h'\fP
.br
\fC#include 'common\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBmpRGBSampleValue\fP"
.br
.RI "a sample in a bmp rgb (i\&.e\&. 24-bit) file "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for steghide from the source code\&.
