.TH "BmpSampleValue.h" 3 "Thu Aug 17 2017" "Version 0.5.1" "steghide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BmpSampleValue.h
.SH SYNOPSIS
.br
.PP
\fC#include 'SampleValue\&.h'\fP
.br
\fC#include 'common\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBmpSampleValue\fP"
.br
.RI "an (abstract) sample value in a bmp file "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for steghide from the source code\&.
