.TH "CvrStgFile::Property" 3 "Thu Aug 17 2017" "Version 0.5.1" "steghide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CvrStgFile::Property
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <CvrStgFile\&.h>\fP
.PP
Inherits pair< std::string, std::string >\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBProperty\fP (std::string key, std::string value)"
.br
.ti -1c
.RI "std::string \fBgetKey\fP (void) const"
.br
.ti -1c
.RI "std::string \fBgetValue\fP (void) const"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CvrStgFile::Property::Property (std::string key, std::string value)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "std::string CvrStgFile::Property::getKey (void) const\fC [inline]\fP"

.SS "std::string CvrStgFile::Property::getValue (void) const\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for steghide from the source code\&.
