.TH "CvrStgObject.h" 3 "Thu Aug 17 2017" "Version 0.5.1" "steghide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CvrStgObject.h
.SH SYNOPSIS
.br
.PP
\fC#include 'common\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCvrStgObject\fP"
.br
.RI "an object that can hold embedded data "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for steghide from the source code\&.
