.TH "DFSAPHeuristic.h" 3 "Thu Aug 17 2017" "Version 0.5.1" "steghide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DFSAPHeuristic.h
.SH SYNOPSIS
.br
.PP
\fC#include 'EdgeIterator\&.h'\fP
.br
\fC#include 'MatchingAlgorithm\&.h'\fP
.br
\fC#include 'Vertex\&.h'\fP
.br
\fC#include 'Graph\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDFSAPHeuristic\fP"
.br
.RI "a matching algorithm implementing a heuristic search for augmenting paths "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for steghide from the source code\&.
