.TH "DMDConstructionHeuristic.h" 3 "Thu Aug 17 2017" "Version 0.5.1" "steghide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DMDConstructionHeuristic.h
.SH SYNOPSIS
.br
.PP
\fC#include 'MatchingAlgorithm\&.h'\fP
.br
\fC#include 'common\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDMDConstructionHeuristic\fP"
.br
.RI "an implementation of the 'dynamic minimum degree' heuristic for contruction a matching "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for steghide from the source code\&.
