.TH "DummySampleValue" 3 "Thu Aug 17 2017" "Version 0.5.1" "steghide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DummySampleValue
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <DummySampleValue\&.h>\fP
.PP
Inherits \fBSampleValue\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDummySampleValue\fP (\fBUWORD16\fP v)"
.br
.ti -1c
.RI "\fBUWORD16\fP \fBgetValue\fP (void) const"
.br
.ti -1c
.RI "\fBUWORD32\fP \fBcalcDistance\fP (const \fBSampleValue\fP *s) const"
.br
.ti -1c
.RI "bool \fBisNeighbour\fP (const \fBSampleValue\fP *s) const"
.br
.ti -1c
.RI "\fBSampleValue\fP * \fBgetNearestTargetSampleValue\fP (\fBEmbValue\fP t) const"
.br
.ti -1c
.RI "std::string \fBgetName\fP (void) const"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBUWORD16\fP \fBValue\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "DummySampleValue::DummySampleValue (\fBUWORD16\fP v)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBUWORD32\fP DummySampleValue::calcDistance (const \fBSampleValue\fP * s) const\fC [virtual]\fP"
calculate the distance as | Value - s->Value | 
.PP
Implements \fBSampleValue\fP\&.
.SS "std::string DummySampleValue::getName (void) const\fC [virtual]\fP"
return a short name uniquely identifying this sample value 
.PP
Implements \fBSampleValue\fP\&.
.SS "\fBSampleValue\fP * DummySampleValue::getNearestTargetSampleValue (\fBEmbValue\fP t) const\fC [virtual]\fP"
get the nearest (with the least distance to this sample value) sample value whose embedded value equals the specified target 
.PP
\fBParameters:\fP
.RS 4
\fIt\fP the target embedded value
.RE
.PP
If two or more target sample values have equal distance each of them should be returned with equal probability\&.
.PP
The returned \fBSampleValue\fP object should be deleted by the callser\&. 
.PP
Implements \fBSampleValue\fP\&.
.SS "\fBUWORD16\fP DummySampleValue::getValue (void) const\fC [inline]\fP"

.SS "bool DummySampleValue::isNeighbour (const \fBSampleValue\fP * s) const\fC [virtual]\fP"
return from the contents of the SampleValueAdjacencyMatrix in the \fBDummyFile\fP 
.PP
Reimplemented from \fBSampleValue\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBUWORD16\fP DummySampleValue::Value\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for steghide from the source code\&.
