.TH "EdgeIterator.h" 3 "Thu Aug 17 2017" "Version 0.5.1" "steghide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EdgeIterator.h
.SH SYNOPSIS
.br
.PP
\fC#include <list>\fP
.br
\fC#include 'Edge\&.h'\fP
.br
\fC#include 'SampleOccurence\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBEdgeIterator\fP"
.br
.RI "allows an iteration trough all edges of a vertex "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for steghide from the source code\&.
