.TH "EmbData.h" 3 "Thu Aug 17 2017" "Version 0.5.1" "steghide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EmbData.h
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include <vector>\fP
.br
\fC#include 'common\&.h'\fP
.br
\fC#include 'BitString\&.h'\fP
.br
\fC#include 'EncryptionAlgorithm\&.h'\fP
.br
\fC#include 'EncryptionMode\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBEmbData\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for steghide from the source code\&.
