.TH "Embedder.cc" 3 "Thu Aug 17 2017" "Version 0.5.1" "steghide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Embedder.cc
.SH SYNOPSIS
.br
.PP
\fC#include <cfloat>\fP
.br
\fC#include <cstdlib>\fP
.br
\fC#include 'DFSAPHeuristic\&.h'\fP
.br
\fC#include 'BitString\&.h'\fP
.br
\fC#include 'CvrStgFile\&.h'\fP
.br
\fC#include 'DMDConstructionHeuristic\&.h'\fP
.br
\fC#include 'EmbData\&.h'\fP
.br
\fC#include 'Embedder\&.h'\fP
.br
\fC#include 'Edge\&.h'\fP
.br
\fC#include 'Graph\&.h'\fP
.br
\fC#include 'Matching\&.h'\fP
.br
\fC#include 'ProgressOutput\&.h'\fP
.br
\fC#include 'Selector\&.h'\fP
.br
\fC#include 'Vertex\&.h'\fP
.br
\fC#include 'WKSConstructionHeuristic\&.h'\fP
.br
\fC#include 'common\&.h'\fP
.br
\fC#include 'error\&.h'\fP
.br
\fC#include 'msg\&.h'\fP
.br

.SS "Variables"

.in +1c
.ti -1c
.RI "\fBGlobals\fP \fBGlobs\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "\fBGlobals\fP Globs"

.SH "Author"
.PP 
Generated automatically by Doxygen for steghide from the source code\&.
