.TH "EncryptionMode::struct_Translation" 3 "Thu Aug 17 2017" "Version 0.5.1" "steghide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EncryptionMode::struct_Translation
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBIRep\fP \fBirep\fP"
.br
.ti -1c
.RI "char * \fBsrep\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBIRep\fP EncryptionMode::struct_Translation::irep"

.SS "char* EncryptionMode::struct_Translation::srep"


.SH "Author"
.PP 
Generated automatically by Doxygen for steghide from the source code\&.
