.TH "error.h" 3 "Thu Aug 17 2017" "Version 0.5.1" "steghide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
error.h
.SH SYNOPSIS
.br
.PP
\fC#include <cstdio>\fP
.br
\fC#include <string>\fP
.br
\fC#include 'SteghideError\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBArgError\fP"
.br
.ti -1c
.RI "class \fBBinaryInputError\fP"
.br
.ti -1c
.RI "class \fBBinaryOutputError\fP"
.br
.ti -1c
.RI "class \fBUnSupFileFormat\fP"
.br
.ti -1c
.RI "class \fBNotImplementedError\fP"
.br
.ti -1c
.RI "class \fBCorruptDataError\fP"
.br
.RI "is thrown as exception when corrupt data is encountered during extraction "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for steghide from the source code\&.
