.TH "Extractor" 3 "Thu Aug 17 2017" "Version 0.5.1" "steghide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Extractor
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Extractor\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBExtractor\fP (std::string stgfn, std::string pp)"
.br
.ti -1c
.RI "\fBEmbData\fP * \fBextract\fP (void)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "std::string \fBStegoFileName\fP"
.br
.ti -1c
.RI "std::string \fBPassphrase\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Extractor::Extractor (std::string stgfn, std::string pp)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBEmbData\fP * Extractor::extract (void)"

.SH "Member Data Documentation"
.PP 
.SS "std::string Extractor::Passphrase\fC [private]\fP"

.SS "std::string Extractor::StegoFileName\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for steghide from the source code\&.
