.TH "Graph.h" 3 "Thu Aug 17 2017" "Version 0.5.1" "steghide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Graph.h
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <list>\fP
.br
\fC#include <map>\fP
.br
\fC#include <queue>\fP
.br
\fC#include <vector>\fP
.br
\fC#include 'EdgeIterator\&.h'\fP
.br
\fC#include 'SampleValueAdjacencyList\&.h'\fP
.br
\fC#include 'common\&.h'\fP
.br
\fC#include 'wrapper_hash_set\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBGraph\fP"
.br
.RI "a graph constructed from a cover file and a message to be embedded "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for steghide from the source code\&.
