.TH "JpegSampleValue.cc" 3 "Thu Aug 17 2017" "Version 0.5.1" "steghide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JpegSampleValue.cc
.SH SYNOPSIS
.br
.PP
\fC#include <cstdlib>\fP
.br
\fC#include <cmath>\fP
.br
\fC#include 'common\&.h'\fP
.br
\fC#include 'JpegSampleValue\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for steghide from the source code\&.
