.TH "JpegFileTest" 3 "Thu Aug 17 2017" "Version 0.5.1" "steghide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JpegFileTest
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <JpegFileTest\&.h>\fP
.PP
Inherits \fBCvrStgFileTest\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBJpegFileTest\fP (\fBTestSuite\fP *s)"
.br
.ti -1c
.RI "void \fBsetup\fP (void)"
.br
.ti -1c
.RI "void \fBcleanup\fP (void)"
.br
.ti -1c
.RI "void \fBtestReadEmbedExtract\fP (void)"
.br
.ti -1c
.RI "void \fBtestReadEmbedWriteReadExtract\fP (void)"
.br
.ti -1c
.RI "void \fBtestPosition\fP (void)"
.br
.ti -1c
.RI "void \fBtestReadExtractCompare\fP (void)"
.br
.ti -1c
.RI "void \fBtestEmbeddedValue\fP (void)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBBitString\fP * \fBbs1\fP"
.br
.ti -1c
.RI "\fBBitString\fP * \fBbs2\fP"
.br
.ti -1c
.RI "\fBCvrStgFile\fP * \fBf1\fP"
.br
.ti -1c
.RI "\fBCvrStgFile\fP * \fBf2\fP"
.br
.ti -1c
.RI "\fBGlobals\fP \fBgl1\fP"
.br
.ti -1c
.RI "\fBGlobals\fP \fBgl2\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "JpegFileTest::JpegFileTest (\fBTestSuite\fP * s)"

.SH "Member Function Documentation"
.PP 
.SS "void JpegFileTest::cleanup (void)\fC [virtual]\fP"
cleanup the unit test - called after run 
.PP
Reimplemented from \fBUnitTest\fP\&.
.SS "void JpegFileTest::setup (void)\fC [virtual]\fP"
setup the unit test - called before run
.PP
\fBUnitTest::setup\fP will (together with \fBUnitTest::cleanup\fP) save and restore the object stored in Globs so they should be called from the corresponding functions in the derived object if the derived unit test manipulates the Globs object\&. 
.PP
Reimplemented from \fBUnitTest\fP\&.
.SS "void JpegFileTest::testEmbeddedValue (void)"

.SS "void JpegFileTest::testPosition (void)"

.SS "void JpegFileTest::testReadEmbedExtract (void)"

.SS "void JpegFileTest::testReadEmbedWriteReadExtract (void)"

.SS "void JpegFileTest::testReadExtractCompare (void)"

.SH "Member Data Documentation"
.PP 
.SS "\fBBitString\fP* JpegFileTest::bs1\fC [private]\fP"

.SS "\fBBitString\fP * JpegFileTest::bs2\fC [private]\fP"

.SS "\fBCvrStgFile\fP* JpegFileTest::f1\fC [private]\fP"

.SS "\fBCvrStgFile\fP * JpegFileTest::f2\fC [private]\fP"

.SS "\fBGlobals\fP JpegFileTest::gl1\fC [private]\fP"

.SS "\fBGlobals\fP JpegFileTest::gl2\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for steghide from the source code\&.
