.TH "MatchingTest.cc" 3 "Thu Aug 17 2017" "Version 0.5.1" "steghide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MatchingTest.cc
.SH SYNOPSIS
.br
.PP
\fC#include 'BitString\&.h'\fP
.br
\fC#include 'Edge\&.h'\fP
.br
\fC#include 'Graph\&.h'\fP
.br
\fC#include 'Selector\&.h'\fP
.br
\fC#include 'DummyFile\&.h'\fP
.br
\fC#include 'MatchingTest\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBCREATEEDGEPTR\fP(G,  V1,  V2)   (new \fBEdge\fP ((G)\->getVertex(V1), 0, (G)\->getVertex(V2), 1))"
.br
.ti -1c
.RI "#define \fBCREATEEDGEOBJ\fP(G,  V1,  V2)   (\fBEdge\fP ((G)\->getVertex(V1), 0, (G)\->getVertex(V2), 1))"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define CREATEEDGEOBJ(G, V1, V2)   (\fBEdge\fP ((G)\->getVertex(V1), 0, (G)\->getVertex(V2), 1))"

.SS "#define CREATEEDGEPTR(G, V1, V2)   (new \fBEdge\fP ((G)\->getVertex(V1), 0, (G)\->getVertex(V2), 1))"

.SH "Author"
.PP 
Generated automatically by Doxygen for steghide from the source code\&.
