.TH "Matching.h" 3 "Thu Aug 17 2017" "Version 0.5.1" "steghide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Matching.h
.SH SYNOPSIS
.br
.PP
\fC#include <list>\fP
.br
\fC#include <vector>\fP
.br
\fC#include 'Vertex\&.h'\fP
.br
\fC#include 'common\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMatching\fP"
.br
.RI "represent a matching on a graph "
.ti -1c
.RI "class \fBMatching::VertexInfo\fP"
.br
.RI "contains information about a vertex that is possibly in a matching "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for steghide from the source code\&.
