.TH "MatchingTest" 3 "Thu Aug 17 2017" "Version 0.5.1" "steghide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MatchingTest
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <MatchingTest\&.h>\fP
.PP
Inherits \fBUnitTest\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMatchingTest\fP (\fBTestSuite\fP *s)"
.br
.ti -1c
.RI "void \fBsetup\fP (void)"
.br
.ti -1c
.RI "void \fBcleanup\fP (void)"
.br
.ti -1c
.RI "void \fBtestAddRemoveEdge\fP (void)"
.br
.ti -1c
.RI "void \fBtestAugmentingPath\fP (void)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBBitString\fP * \fBbs1\fP"
.br
.ti -1c
.RI "\fBBitString\fP * \fBbs2\fP"
.br
.ti -1c
.RI "\fBCvrStgFile\fP * \fBf1\fP"
.br
.ti -1c
.RI "\fBCvrStgFile\fP * \fBf2\fP"
.br
.ti -1c
.RI "\fBSelector\fP * \fBs1\fP"
.br
.ti -1c
.RI "\fBSelector\fP * \fBs2\fP"
.br
.ti -1c
.RI "\fBGraph\fP * \fBg1\fP"
.br
.ti -1c
.RI "\fBGraph\fP * \fBg2\fP"
.br
.ti -1c
.RI "\fBMatching\fP * \fBm1\fP"
.br
.ti -1c
.RI "\fBMatching\fP * \fBm2\fP"
.br
.ti -1c
.RI "\fBGlobals\fP \fBgl1\fP"
.br
.ti -1c
.RI "\fBGlobals\fP \fBgl2\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "MatchingTest::MatchingTest (\fBTestSuite\fP * s)"

.SH "Member Function Documentation"
.PP 
.SS "void MatchingTest::cleanup (void)\fC [virtual]\fP"
cleanup the unit test - called after run 
.PP
Reimplemented from \fBUnitTest\fP\&.
.SS "void MatchingTest::setup (void)\fC [virtual]\fP"
setup the unit test - called before run
.PP
\fBUnitTest::setup\fP will (together with \fBUnitTest::cleanup\fP) save and restore the object stored in Globs so they should be called from the corresponding functions in the derived object if the derived unit test manipulates the Globs object\&. 
.PP
Reimplemented from \fBUnitTest\fP\&.
.SS "void MatchingTest::testAddRemoveEdge (void)"

.SS "void MatchingTest::testAugmentingPath (void)"

.SH "Member Data Documentation"
.PP 
.SS "\fBBitString\fP* MatchingTest::bs1\fC [private]\fP"

.SS "\fBBitString\fP * MatchingTest::bs2\fC [private]\fP"

.SS "\fBCvrStgFile\fP* MatchingTest::f1\fC [private]\fP"

.SS "\fBCvrStgFile\fP * MatchingTest::f2\fC [private]\fP"

.SS "\fBGraph\fP* MatchingTest::g1\fC [private]\fP"

.SS "\fBGraph\fP * MatchingTest::g2\fC [private]\fP"

.SS "\fBGlobals\fP MatchingTest::gl1\fC [private]\fP"

.SS "\fBGlobals\fP MatchingTest::gl2\fC [private]\fP"

.SS "\fBMatching\fP* MatchingTest::m1\fC [private]\fP"

.SS "\fBMatching\fP * MatchingTest::m2\fC [private]\fP"

.SS "\fBSelector\fP* MatchingTest::s1\fC [private]\fP"

.SS "\fBSelector\fP * MatchingTest::s2\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for steghide from the source code\&.
