.TH "MCryptPPTest" 3 "Thu Aug 17 2017" "Version 0.5.1" "steghide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MCryptPPTest
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <MCryptPPTest\&.h>\fP
.PP
Inherits \fBUnitTest\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMCryptPPTest\fP (\fBTestSuite\fP *s)"
.br
.ti -1c
.RI "void \fBtestEncryption\fP (void)"
.br
.ti -1c
.RI "void \fBtestDecryption\fP (void)"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "bool \fBgenericTestEncryption\fP ()"
.br
.ti -1c
.RI "bool \fBgenericTestDecryption\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "MCryptPPTest::MCryptPPTest (\fBTestSuite\fP * s)"

.SH "Member Function Documentation"
.PP 
.SS "bool MCryptPPTest::genericTestDecryption ()\fC [private]\fP"

.SS "bool MCryptPPTest::genericTestEncryption ()\fC [private]\fP"

.SS "void MCryptPPTest::testDecryption (void)"

.SS "void MCryptPPTest::testEncryption (void)"


.SH "Author"
.PP 
Generated automatically by Doxygen for steghide from the source code\&.
