.TH "msg.h" 3 "Thu Aug 17 2017" "Version 0.5.1" "steghide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
msg.h
.SH SYNOPSIS
.br
.PP
\fC#include <cstdarg>\fP
.br
\fC#include <string>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMessageBase\fP"
.br
.ti -1c
.RI "class \fBMessage\fP"
.br
.ti -1c
.RI "class \fBVerboseMessage\fP"
.br
.ti -1c
.RI "class \fBWarning\fP"
.br
.ti -1c
.RI "class \fBCriticalWarning\fP"
.br
.ti -1c
.RI "class \fBQuestion\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for steghide from the source code\&.
