.TH "RandomSource.h" 3 "Thu Aug 17 2017" "Version 0.5.1" "steghide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RandomSource.h
.SH SYNOPSIS
.br
.PP
\fC#include <cstdio>\fP
.br
\fC#include <vector>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBRandomSource\fP"
.br
.RI "objects of this class are used as a source of random (non reproduceable) data "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for steghide from the source code\&.
