.TH "RandomSource.cc" 3 "Thu Aug 17 2017" "Version 0.5.1" "steghide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RandomSource.cc
.SH SYNOPSIS
.br
.PP
\fC#include <cstdlib>\fP
.br
\fC#include <ctime>\fP
.br
\fC#include 'BitString\&.h'\fP
.br
\fC#include 'common\&.h'\fP
.br
\fC#include 'error\&.h'\fP
.br
\fC#include 'msg\&.h'\fP
.br
\fC#include 'RandomSource\&.h'\fP
.br

.SS "Variables"

.in +1c
.ti -1c
.RI "\fBRandomSource\fP \fBRndSrc\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "\fBRandomSource\fP RndSrc"

.SH "Author"
.PP 
Generated automatically by Doxygen for steghide from the source code\&.
