.TH "SampleValue.h" 3 "Thu Aug 17 2017" "Version 0.5.1" "steghide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SampleValue.h
.SH SYNOPSIS
.br
.PP
\fC#include <functional>\fP
.br
\fC#include 'common\&.h'\fP
.br
\fC#include 'wrapper_hash_set\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSampleValue\fP"
.br
.RI "the value of a sample in a \fBCvrStgFile\fP "
.ti -1c
.RI "struct \fBSampleValuesEqual\fP"
.br
.ti -1c
.RI "struct \fBSampleValuesLess\fP"
.br
.ti -1c
.RI "struct \fBSampleValueHash\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for steghide from the source code\&.
