.TH "SampleValuesLess" 3 "Thu Aug 17 2017" "Version 0.5.1" "steghide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SampleValuesLess
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SampleValue\&.h>\fP
.PP
Inherits binary_function< SampleValue *, SampleValue *, bool >\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBoperator()\fP (const \fBSampleValue\fP *s1, const \fBSampleValue\fP *s2) const"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "bool SampleValuesLess::operator() (const \fBSampleValue\fP * s1, const \fBSampleValue\fP * s2) const\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for steghide from the source code\&.
