.TH "Session" 3 "Thu Aug 17 2017" "Version 0.5.1" "steghide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Session
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Session\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSession\fP (void)"
.br
.ti -1c
.RI "void \fBrun\fP (void)"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "std::string \fBstripDir\fP (std::string s) const"
.br
.ti -1c
.RI "void \fBprintInfo\fP (void)"
.br
.ti -1c
.RI "void \fBprintEncInfo\fP (void)"
.br
.ti -1c
.RI "void \fBprintVersion\fP (void)"
.br
.ti -1c
.RI "void \fBprintHelp\fP (void)"
.br
.ti -1c
.RI "void \fBprintLicense\fP (void)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Session::Session (void)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void Session::printEncInfo (void)\fC [private]\fP"

.SS "void Session::printHelp (void)\fC [private]\fP"

.SS "void Session::printInfo (void)\fC [private]\fP"

.SS "void Session::printLicense (void)\fC [private]\fP"

.SS "void Session::printVersion (void)\fC [private]\fP"

.SS "void Session::run (void)"

.SS "std::string Session::stripDir (std::string s) const\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for steghide from the source code\&.
