.TH "SMDConstructionHeuristic::SmallerVertexDegree" 3 "Thu Aug 17 2017" "Version 0.5.1" "steghide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SMDConstructionHeuristic::SmallerVertexDegree
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBoperator()\fP (const \fBVertex\fP *v1, const \fBVertex\fP *v2)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "bool SMDConstructionHeuristic::SmallerVertexDegree::operator() (const \fBVertex\fP * v1, const \fBVertex\fP * v2)\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for steghide from the source code\&.
