.TH "main.cc" 3 "Thu Aug 17 2017" "Version 0.5.1" "steghide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
main.cc
.SH SYNOPSIS
.br
.PP
\fC#include <cstdlib>\fP
.br
\fC#include <clocale>\fP
.br
\fC#include 'common\&.h'\fP
.br
\fC#include 'Session\&.h'\fP
.br
\fC#include 'SteghideError\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "static void \fBgettext_init\fP (void)"
.br
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "static void gettext_init (void)\fC [static]\fP"

.SS "int main (int argc, char * argv[])"

.SH "Author"
.PP 
Generated automatically by Doxygen for steghide from the source code\&.
