.TH "Terminal" 3 "Thu Aug 17 2017" "Version 0.5.1" "steghide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Terminal \- provides some terminal access  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Terminal\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTerminal\fP (void)"
.br
.ti -1c
.RI "void \fBEchoOff\fP (void)"
.br
.ti -1c
.RI "void \fBSingleKeyOn\fP (void)"
.br
.ti -1c
.RI "void \fBreset\fP (void)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Terminal::Terminal (void)"

.SH "Member Function Documentation"
.PP 
.SS "void Terminal::EchoOff (void)"

.SS "void Terminal::reset (void)"

.SS "void Terminal::SingleKeyOn (void)"


.SH "Author"
.PP 
Generated automatically by Doxygen for steghide from the source code\&.
