.TH "TestCategory" 3 "Thu Aug 17 2017" "Version 0.5.1" "steghide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TestCategory
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <TestCategory\&.h>\fP
.PP
Inherits \fBTest\fP\&.
.PP
Inherited by \fBTestCategoryCaller< UTType >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTestCategory\fP (const std::string &n, \fBTestSuite\fP *s)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TestCategory::TestCategory (const std::string & n, \fBTestSuite\fP * s)\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for steghide from the source code\&.
