.TH "main.cc" 3 "Thu Aug 17 2017" "Version 0.5.1" "steghide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
main.cc
.SH SYNOPSIS
.br
.PP
\fC#include <cstdlib>\fP
.br
\fC#include 'common\&.h'\fP
.br
\fC#include 'TestSuite\&.h'\fP
.br
\fC#include 'AudioSampleValueTest\&.h'\fP
.br
\fC#include 'AuFileTest\&.h'\fP
.br
\fC#include 'AUtilsTest\&.h'\fP
.br
\fC#include 'BFSAPHeuristicTest\&.h'\fP
.br
\fC#include 'BitStringTest\&.h'\fP
.br
\fC#include 'BmpFileTest\&.h'\fP
.br
\fC#include 'BmpRGBSampleValueTest\&.h'\fP
.br
\fC#include 'BmpPaletteSampleValueTest\&.h'\fP
.br
\fC#include 'BmpOS2FileTest\&.h'\fP
.br
\fC#include 'BmpWinFileTest\&.h'\fP
.br
\fC#include 'DFSAPHeuristicTest\&.h'\fP
.br
\fC#include 'EdgeIteratorTest\&.h'\fP
.br
\fC#include 'EmbDataTest\&.h'\fP
.br
\fC#include 'WKSConstructionHeuristicTest\&.h'\fP
.br
\fC#include 'GraphTest\&.h'\fP
.br
\fC#include 'JpegFileTest\&.h'\fP
.br
\fC#include 'JpegSampleValueTest\&.h'\fP
.br
\fC#include 'MatchingTest\&.h'\fP
.br
\fC#include 'MCryptPPTest\&.h'\fP
.br
\fC#include 'MHashKeyGenTest\&.h'\fP
.br
\fC#include 'MHashPPTest\&.h'\fP
.br
\fC#include 'SampleValueAdjacencyListTest\&.h'\fP
.br
\fC#include 'SelectorTest\&.h'\fP
.br
\fC#include 'WavFileTest\&.h'\fP
.br
\fC#include 'WavPCMSampleValueTest\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "bool \fBArgVerbose\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char * argv[])"

.SH "Variable Documentation"
.PP 
.SS "bool ArgVerbose"

.SH "Author"
.PP 
Generated automatically by Doxygen for steghide from the source code\&.
