.TH "UnSupFileFormat" 3 "Thu Aug 17 2017" "Version 0.5.1" "steghide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnSupFileFormat
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <error\&.h>\fP
.PP
Inherits \fBSteghideError\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBUnSupFileFormat\fP (\fBBinaryIO\fP *io)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "UnSupFileFormat::UnSupFileFormat (\fBBinaryIO\fP * io)"


.SH "Author"
.PP 
Generated automatically by Doxygen for steghide from the source code\&.
