.TH "utcommon.h" 3 "Thu Aug 17 2017" "Version 0.5.1" "steghide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
utcommon.h
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBDATADIR\fP   '\&./data/'"
.br
.ti -1c
.RI "#define \fBREMOVE\fP   'rm \-f'"
.br
.ti -1c
.RI "#define \fBCOMPARE\fP   'cmp \-s'"
.br
.ti -1c
.RI "#define \fBCOPY\fP   'cp'"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "bool \fBArgVerbose\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define COMPARE   'cmp \-s'"

.SS "#define COPY   'cp'"

.SS "#define DATADIR   '\&./data/'"

.SS "#define REMOVE   'rm \-f'"

.SH "Variable Documentation"
.PP 
.SS "bool ArgVerbose"

.SH "Author"
.PP 
Generated automatically by Doxygen for steghide from the source code\&.
