.TH "Utils" 3 "Thu Aug 17 2017" "Version 0.5.1" "steghide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Utils
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Utils\&.h>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static std::string \fBformatHRSize\fP (unsigned long size)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "std::string Utils::formatHRSize (unsigned long size)\fC [static]\fP"
gets a number of bytes and returns a human-readable string like e\&.g\&. '3,5 KB' 

.SH "Author"
.PP 
Generated automatically by Doxygen for steghide from the source code\&.
