.TH "Vertex.cc" 3 "Thu Aug 17 2017" "Version 0.5.1" "steghide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Vertex.cc
.SH SYNOPSIS
.br
.PP
\fC#include 'AUtils\&.h'\fP
.br
\fC#include 'Edge\&.h'\fP
.br
\fC#include 'EdgeIterator\&.h'\fP
.br
\fC#include 'Graph\&.h'\fP
.br
\fC#include 'Vertex\&.h'\fP
.br
\fC#include 'common\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBBMINUS\fP(A,  B)   ((A > B) ? (A \- B) : (0))"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define BMINUS(A, B)   ((A > B) ? (A \- B) : (0))"

.SH "Author"
.PP 
Generated automatically by Doxygen for steghide from the source code\&.
