.TH "Warning" 3 "Thu Aug 17 2017" "Version 0.5.1" "steghide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Warning
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <msg\&.h>\fP
.PP
Inherits \fBMessageBase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBWarning\fP (void)"
.br
.ti -1c
.RI "\fBWarning\fP (std::string msg)"
.br
.ti -1c
.RI "\fBWarning\fP (const char *msgfmt,\&.\&.\&.)"
.br
.ti -1c
.RI "void \fBprintMessage\fP (void) const"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Warning::Warning (void)\fC [inline]\fP"

.SS "Warning::Warning (std::string msg)\fC [inline]\fP"

.SS "Warning::Warning (const char * msgfmt,  \&.\&.\&.)"

.SH "Member Function Documentation"
.PP 
.SS "void Warning::printMessage (void) const\fC [virtual]\fP"

.PP
Implements \fBMessageBase\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for steghide from the source code\&.
