.TH "WavChunkHeader.cc" 3 "Thu Aug 17 2017" "Version 0.5.1" "steghide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WavChunkHeader.cc
.SH SYNOPSIS
.br
.PP
\fC#include 'BinaryIO\&.h'\fP
.br
\fC#include 'WavChunkHeader\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for steghide from the source code\&.
