.TH "WavFile.cc" 3 "Thu Aug 17 2017" "Version 0.5.1" "steghide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WavFile.cc
.SH SYNOPSIS
.br
.PP
\fC#include <cstdio>\fP
.br
\fC#include <cstdlib>\fP
.br
\fC#include <cstring>\fP
.br
\fC#include 'CvrStgFile\&.h'\fP
.br
\fC#include 'DFSAPHeuristic\&.h'\fP
.br
\fC#include 'SampleValueAdjacencyList\&.h'\fP
.br
\fC#include 'SMDConstructionHeuristic\&.h'\fP
.br
\fC#include 'WavFormatChunk\&.h'\fP
.br
\fC#include 'WavChunkHeader\&.h'\fP
.br
\fC#include 'WavChunkUnused\&.h'\fP
.br
\fC#include 'WavFile\&.h'\fP
.br
\fC#include 'WavPCMSampleValue\&.h'\fP
.br
\fC#include 'common\&.h'\fP
.br
\fC#include 'error\&.h'\fP
.br
\fC#include 'msg\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for steghide from the source code\&.
