.TH "WavFormatChunk.h" 3 "Thu Aug 17 2017" "Version 0.5.1" "steghide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WavFormatChunk.h
.SH SYNOPSIS
.br
.PP
\fC#include 'common\&.h'\fP
.br
\fC#include 'WavChunk\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBWavFormatChunk\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for steghide from the source code\&.
