.TH "WavFileTest.cc" 3 "Thu Aug 17 2017" "Version 0.5.1" "steghide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WavFileTest.cc
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include 'Graph\&.h'\fP
.br
\fC#include 'WavPCMSampleValue\&.h'\fP
.br
\fC#include 'WavFileTest\&.h'\fP
.br
\fC#include 'utcommon\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for steghide from the source code\&.
