.TH "WavFileTest.h" 3 "Thu Aug 17 2017" "Version 0.5.1" "steghide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WavFileTest.h
.SH SYNOPSIS
.br
.PP
\fC#include 'CvrStgFileTest\&.h'\fP
.br
\fC#include 'Selector\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBWavFileTest\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for steghide from the source code\&.
