.TH "WavPCMSmaller" 3 "Thu Aug 17 2017" "Version 0.5.1" "steghide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WavPCMSmaller
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <WavPCMSampleValue\&.h>\fP
.PP
Inherits binary_function< WavPCMSampleValue *, WavPCMSampleValue *, bool >\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBoperator()\fP (const \fBWavPCMSampleValue\fP *v, const \fBWavPCMSampleValue\fP *w)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "bool WavPCMSmaller::operator() (const \fBWavPCMSampleValue\fP * v, const \fBWavPCMSampleValue\fP * w)\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for steghide from the source code\&.
