.TH "WavPCMSampleValueTest" 3 "Thu Aug 17 2017" "Version 0.5.1" "steghide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WavPCMSampleValueTest
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <WavPCMSampleValueTest\&.h>\fP
.PP
Inherits \fBSampleValueTest\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBWavPCMSampleValueTest\fP (\fBTestSuite\fP *s)"
.br
.ti -1c
.RI "void \fBsetup\fP (void)"
.br
.ti -1c
.RI "void \fBcleanup\fP (void)"
.br
.ti -1c
.RI "void \fBtestDistance\fP (void)"
.br
.ti -1c
.RI "void \fBtestIsNeighbour\fP (void)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBCvrStgFile\fP * \fBf_WavPCM8\fP"
.br
.ti -1c
.RI "\fBCvrStgFile\fP * \fBf_WavPCM16\fP"
.br
.ti -1c
.RI "\fBSampleValue\fP * \fBsv_WavPCM8_0\fP"
.br
.ti -1c
.RI "\fBSampleValue\fP * \fBsv_WavPCM8_1\fP"
.br
.ti -1c
.RI "\fBSampleValue\fP * \fBsv_WavPCM8_45\fP"
.br
.ti -1c
.RI "\fBSampleValue\fP * \fBsv_WavPCM16_m32768\fP"
.br
.ti -1c
.RI "\fBSampleValue\fP * \fBsv_WavPCM16_32767\fP"
.br
.ti -1c
.RI "\fBSampleValue\fP * \fBsv_WavPCM16_0\fP"
.br
.ti -1c
.RI "\fBSampleValue\fP * \fBsv_WavPCM16_15\fP"
.br
.ti -1c
.RI "\fBGlobals\fP \fBgl_WavPCM8\fP"
.br
.ti -1c
.RI "\fBGlobals\fP \fBgl_WavPCM16\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "WavPCMSampleValueTest::WavPCMSampleValueTest (\fBTestSuite\fP * s)"

.SH "Member Function Documentation"
.PP 
.SS "void WavPCMSampleValueTest::cleanup (void)\fC [virtual]\fP"
cleanup the unit test - called after run 
.PP
Reimplemented from \fBUnitTest\fP\&.
.SS "void WavPCMSampleValueTest::setup (void)\fC [virtual]\fP"
setup the unit test - called before run
.PP
\fBUnitTest::setup\fP will (together with \fBUnitTest::cleanup\fP) save and restore the object stored in Globs so they should be called from the corresponding functions in the derived object if the derived unit test manipulates the Globs object\&. 
.PP
Reimplemented from \fBUnitTest\fP\&.
.SS "void WavPCMSampleValueTest::testDistance (void)"

.SS "void WavPCMSampleValueTest::testIsNeighbour (void)"

.SH "Member Data Documentation"
.PP 
.SS "\fBCvrStgFile\fP * WavPCMSampleValueTest::f_WavPCM16\fC [private]\fP"

.SS "\fBCvrStgFile\fP* WavPCMSampleValueTest::f_WavPCM8\fC [private]\fP"

.SS "\fBGlobals\fP WavPCMSampleValueTest::gl_WavPCM16\fC [private]\fP"

.SS "\fBGlobals\fP WavPCMSampleValueTest::gl_WavPCM8\fC [private]\fP"

.SS "\fBSampleValue\fP * WavPCMSampleValueTest::sv_WavPCM16_0\fC [private]\fP"

.SS "\fBSampleValue\fP * WavPCMSampleValueTest::sv_WavPCM16_15\fC [private]\fP"

.SS "\fBSampleValue\fP * WavPCMSampleValueTest::sv_WavPCM16_32767\fC [private]\fP"

.SS "\fBSampleValue\fP * WavPCMSampleValueTest::sv_WavPCM16_m32768\fC [private]\fP"

.SS "\fBSampleValue\fP* WavPCMSampleValueTest::sv_WavPCM8_0\fC [private]\fP"

.SS "\fBSampleValue\fP * WavPCMSampleValueTest::sv_WavPCM8_1\fC [private]\fP"

.SS "\fBSampleValue\fP * WavPCMSampleValueTest::sv_WavPCM8_45\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for steghide from the source code\&.
