.TH "WavPCMSampleValue.h" 3 "Thu Aug 17 2017" "Version 0.5.1" "steghide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WavPCMSampleValue.h
.SH SYNOPSIS
.br
.PP
\fC#include <functional>\fP
.br
\fC#include 'SampleValue\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBWavPCMSampleValue\fP"
.br
.ti -1c
.RI "class \fBWavPCMSmaller\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for steghide from the source code\&.
